export const metadata = {
  title: "Learn NextJS",
  description: "Generated by create next app",
};

export default function RootLayoutFacebook({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
